import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, signOut, sendPasswordResetEmail, createUserWithEmailAndPassword } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-auth.js';
import { getFirestore, collection, doc, onSnapshot, setDoc, deleteDoc, getDocs, updateDoc } from 'https://www.gstatic.com/firebasejs/12.19.0/firebase-firestore.js';
import { firebaseConfig } from './firebase-config.js';
const firebaseApp=initializeApp(firebaseConfig),auth=getAuth(firebaseApp),db=getFirestore(firebaseApp),staffAuth=getAuth(initializeApp(firebaseConfig,'amp-staff-provisioner'));
let signedInUser=null,profileName='',canManageUsers=false,profileUnsubscribe=null,ordersUnsubscribe=null,entryUnsubscribes=new Map(),serverCache=new Map(),pendingWrites=new Set(),initialCloudLoad=true;
const roles={warehouse:'Кладовщик',manager:'Менеджер',director:'Директор'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isoNow=()=>new Date().toISOString();
const fmtDate=d=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d));
const fmtDateTime=d=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(d));
let state={orders:[],notices:[],role:'warehouse',seen:{}};
let activeFilter='all', selectedId=null, pendingDefectId=null;
const $=id=>document.getElementById(id), modal=$('modalBackdrop');
function showAuth(message='Войдите с рабочей учётной записью.'){ $('authGate').hidden=false;document.querySelector('.app-shell').hidden=true;$('authMessage').textContent=message }
function hideAuth(){ $('authGate').hidden=true;document.querySelector('.app-shell').hidden=false }
function entryToCloud(e){const out={kind:e.kind,article:e.article||'',text:e.text||'',authorId:e.authorId||auth.currentUser.uid,authorName:e.author||profileName,createdAt:e.createdAt,photos:e.photos||[]};for(const k of ['decision','decisionText','decidedBy','decidedByName','decidedAt'])if(e[k]!==undefined)out[k]=e[k];return out}
function entryFromCloud(id,d){return{id,kind:d.kind,article:d.article||'',text:d.text||'',authorId:d.authorId,author:d.authorName||'Сотрудник',createdAt:d.createdAt,photos:d.photos||[],...Object.fromEntries(['decision','decisionText','decidedBy','decidedByName','decidedAt'].filter(k=>d[k]!==undefined).map(k=>[k,d[k]]))}}
function orderToCloud(o,isNew=false){return{number:o.number,client:o.client||'',status:o.status,createdAt:o.createdAt,createdBy:o.createdBy||auth.currentUser.uid,createdByName:o.author||profileName,updatedAt:o.updatedAt||o.createdAt,...(!isNew&&o.updatedBy?{updatedBy:o.updatedBy,updatedByName:o.updatedByName}:{})}}
function equal(a,b){return JSON.stringify(a)===JSON.stringify(b)}
async function save(){
 if(!signedInUser)return;
 try{
 const currentIds=new Set(state.orders.map(o=>o.id));
 for(const o of state.orders){
   const base=serverCache.get(o.id),newOrder=!base;
   const next=orderToCloud(o,newOrder),prev=base?orderToCloud(base):null;
   if(!base||!equal(next,prev)){
     if(base){next.updatedAt=isoNow();next.updatedBy=signedInUser.uid;next.updatedByName=profileName;o.updatedAt=next.updatedAt;o.updatedBy=next.updatedBy;o.updatedByName=profileName}
     pendingWrites.add(o.id);await setDoc(doc(db,'orders',o.id),next);pendingWrites.delete(o.id);
     serverCache.set(o.id,{...o,...next,entries:base?.entries||[]});
   }
   const oldEntries=new Map((base?.entries||[]).map(e=>[e.id,e]));
   for(const e of o.entries||[]){const cloud=entryToCloud(e),old=oldEntries.get(e.id);if(!old||!equal(cloud,entryToCloud(old))){await setDoc(doc(db,'orders',o.id,'entries',e.id),cloud);oldEntries.delete(e.id)}else oldEntries.delete(e.id)}
   for(const removedId of oldEntries.keys())await deleteDoc(doc(db,'orders',o.id,'entries',removedId));
   serverCache.set(o.id,{...(serverCache.get(o.id)||o),...o,entries:[...(o.entries||[])]});
 }
 for(const [id,old] of serverCache){if(!currentIds.has(id)&&state.role==='director'){for(const e of old.entries||[])await deleteDoc(doc(db,'orders',id,'entries',e.id));await deleteDoc(doc(db,'orders',id));serverCache.delete(id)}}
 }catch(err){console.error(err);toast('Не удалось сохранить изменения. Проверьте доступ и соединение.');}
}
function stopCloud(){profileUnsubscribe?.();ordersUnsubscribe?.();profileUnsubscribe=ordersUnsubscribe=null;for(const stop of entryUnsubscribes.values())stop();entryUnsubscribes.clear();serverCache.clear();state.orders=[]}
function watchOrders(){
 ordersUnsubscribe?.();
 ordersUnsubscribe=onSnapshot(collection(db,'orders'),snap=>{
   const oldIds=new Set(state.orders.map(o=>o.id)),remoteIds=new Set();
   for(const d of snap.docs){remoteIds.add(d.id);const data=d.data(),prior=serverCache.get(d.id);const order={id:d.id,number:data.number,client:data.client||'',status:data.status,createdAt:data.createdAt,updatedAt:data.updatedAt,author:data.createdByName||'Сотрудник',createdBy:data.createdBy,updatedBy:data.updatedBy,updatedByName:data.updatedByName,entries:prior?.entries||[]};
     const at=state.orders.findIndex(o=>o.id===d.id);if(at<0)state.orders.push(order);else state.orders[at]={...order,entries:state.orders[at].entries||[]};serverCache.set(d.id,{...order,entries:prior?.entries||[]});
     if(!entryUnsubscribes.has(d.id)){let firstEntries=true;entryUnsubscribes.set(d.id,onSnapshot(collection(db,'orders',d.id,'entries'),es=>{const entries=es.docs.map(x=>entryFromCloud(x.id,x.data())).sort((a,b)=>new Date(a.createdAt)-new Date(b.createdAt));const item=state.orders.find(o=>o.id===d.id);if(!item)return;const before=JSON.stringify(item.entries||[]);item.entries=entries;serverCache.set(d.id,{...serverCache.get(d.id),entries:entries.map(x=>({...x}))});if(!initialCloudLoad&&!firstEntries&&before!==JSON.stringify(entries)){const last=entries.at(-1);toast(`Обновлён заказ № ${item.number}${last?`: ${last.author} добавил запись`:''}`);if(document.hidden&&'Notification'in window&&Notification.permission==='granted')new Notification(`Заказ № ${item.number}`,{body:last?.text||item.status,icon:'amp-logo.png'})}firstEntries=false;render()}));}
     if(!initialCloudLoad&&!oldIds.has(d.id)){const message=`Поступил заказ № ${order.number}`;toast(message);notify(message,d.id);if(document.hidden&&'Notification'in window&&Notification.permission==='granted')new Notification(`Новый заказ № ${order.number}`,{body:order.client,icon:'amp-logo.png'})}
   }
   for(const o of [...state.orders])if(!remoteIds.has(o.id)&&!pendingWrites.has(o.id)){state.orders=state.orders.filter(x=>x.id!==o.id);entryUnsubscribes.get(o.id)?.();entryUnsubscribes.delete(o.id);serverCache.delete(o.id)}
   initialCloudLoad=false;render();
 },err=>{console.error(err);toast('Не удалось загрузить общую историю. Проверьте доступ к Firestore.')});
}
onAuthStateChanged(auth,user=>{
 stopCloud();signedInUser=user;initialCloudLoad=true;
 if(!user){showAuth();return}
 showAuth('Проверяем доступ…');
 profileUnsubscribe=onSnapshot(doc(db,'users',user.uid),snap=>{
   if(!snap.exists()){showAuth('Учётная запись создана, но администратор ещё не назначил вам роль.');$('authError').textContent=`UID для администратора: ${user.uid}`;return}
   const profile=snap.data();if(profile.active!==true||!roles[profile.role]){showAuth('Доступ отключён или роль не назначена. Обратитесь к администратору.');return}
   state.role=profile.role;canManageUsers=profile.admin===true||profile.role==='director';profileName=profile.displayName||user.email||roles[profile.role];$('userName').textContent=profileName;$('userRole').textContent=canManageUsers?`Администратор · ${roles[profile.role]}`:roles[profile.role];hideAuth();watchOrders();render();
 },err=>{console.error(err);showAuth('Не удалось проверить профиль сотрудника. Проверьте правила доступа Firestore.')});
});
$('loginForm').addEventListener('submit',async e=>{e.preventDefault();$('authError').textContent='';try{await signInWithEmailAndPassword(auth,$('loginEmail').value.trim(),$('loginPassword').value)}catch(err){$('authError').textContent=({ 'auth/invalid-credential':'Неверная почта или пароль.','auth/too-many-requests':'Слишком много попыток. Попробуйте позже.','auth/network-request-failed':'Нет соединения с интернетом.'}[err.code]||'Не удалось войти. Проверьте почту и пароль.')}});
$('resetPassword').addEventListener('click',async()=>{const email=$('loginEmail').value.trim();if(!email){$('authError').textContent='Сначала укажите рабочую почту.';return}try{await sendPasswordResetEmail(auth,email);$('authError').textContent='Ссылка для сброса пароля отправлена на почту.'}catch(err){$('authError').textContent='Не удалось отправить письмо для сброса пароля.'}});
function initials(name){return String(name).split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()}
function notify(message,orderId){state.notices.unshift({id:crypto.randomUUID(),message,orderId,at:isoNow(),read:false});state.notices=state.notices.slice(0,50);paintNotices()}
function statusClass(s){return({'Собран':'status-assembled','Под вопросом':'status-question','На согласовании':'status-approval','Одобрен на отгрузку клиенту':'status-ready','Отменён':'status-cancel'})[s]||'status-neutral'}
function statusPill(s){return `<span class="status-pill ${statusClass(s)}">${esc(s)}</span>`}
function entriesCount(o){return(o.entries||[]).length}
function render(){const search=$('searchInput').value.toLocaleLowerCase('ru');let orders=[...state.orders].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));if(activeFilter!=='all')orders=orders.filter(o=>o.status===activeFilter);if(search)orders=orders.filter(o=>(o.number+' '+o.client).toLocaleLowerCase('ru').includes(search));$('ordersBody').innerHTML=orders.map(o=>`<tr data-order="${esc(o.id)}"><td><a class="order-number" href="#" data-open="${esc(o.id)}">№ ${esc(o.number)}</a><span class="client-sub">создал ${esc(o.author||'Кладовщик')}</span></td><td><span class="client-name">${esc(o.client)}</span><span class="client-sub">${fmtDateTime(o.createdAt)}</span></td><td>${statusPill(o.status)}</td><td><span class="entry-count">${entriesCount(o)}</span></td><td class="time-cell">${fmtDate(o.createdAt)}</td><td><button class="row-menu" title="Открыть карточку" data-open="${esc(o.id)}">···</button></td></tr>`).join('');const empty=orders.length===0;$('emptyState').classList.toggle('visible',empty);$('ordersBody').style.display=empty?'none':'';$('statTotal').textContent=state.orders.length;$('statQuestions').textContent=state.orders.filter(o=>o.status==='Под вопросом').length;$('statApproval').textContent=state.orders.filter(o=>o.status==='На согласовании').length;$('statReady').textContent=state.orders.filter(o=>o.status==='Одобрен на отгрузку клиенту').length;$('allCount').textContent=state.orders.length;$('questionCount').textContent=state.orders.filter(o=>o.status==='Под вопросом').length;$('listSummary').textContent=`${orders.length} ${plural(orders.length,'заказ','заказа','заказов')}`;$('userName').textContent=profileName||roles[state.role];$('userRole').textContent=canManageUsers?`Администратор · ${roles[state.role]}`:roles[state.role];$('modeLabel').textContent='Общая история';$('modeSub').textContent='Синхронизация включена';$('today').textContent=new Intl.DateTimeFormat('ru-RU',{weekday:'short',day:'numeric',month:'long'}).format(new Date());document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.filter===activeFilter));paintNotices()}
function plural(n,a,b,c){n=Math.abs(n)%100;const d=n%10;return n>10&&n<20?c:d>1&&d<5?b:d===1?a:c}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;$('toastStack').append(t);setTimeout(()=>t.remove(),3500)}
function showModal(title,body,buttons=[],eyebrow='КАРТОЧКА ЗАКАЗА'){ $('modalTitle').textContent=title;$('modalEyebrow').textContent=eyebrow;$('modalBody').innerHTML=body;$('modalFoot').innerHTML=buttons.join('');modal.hidden=false;document.body.style.overflow='hidden'}
function closeModal(){modal.hidden=true;document.body.style.overflow=''}
function button(label,action,cls='small-button'){return `<button class="${cls}" data-action="${action}">${label}</button>`}
function openNewOrder(){if(state.role==='manager'){toast('Создавать карточки в этой версии может кладовщик.');return}showModal('Добавить заказ',`<form id="newOrderForm"><div class="form-grid"><div class="field"><label for="orderNumber">Номер заказа *</label><input id="orderNumber" required placeholder="Например, ЗК-18472" autocomplete="off"></div><div class="field"><label for="clientName">Имя клиента *</label><input id="clientName" required placeholder="Имя или название компании"></div></div><div class="field"><label for="startStatus">Начальный статус</label><select id="startStatus"><option>Собран</option><option>Под вопросом</option></select><span class="field-hint">Выберите «Под вопросом», если добавите дефект или вопрос менеджеру.</span></div><div class="field"><label for="initialComment">Комментарий (необязательно)</label><textarea id="initialComment" placeholder="Короткая заметка по заказу"></textarea></div></form>`,[button('Отмена','close'),button('Создать карточку','create-order','primary-button')],'НОВЫЙ ЗАКАЗ')}
function openOrder(id){const o=state.orders.find(x=>x.id===id);if(!o)return;selectedId=id;const isManager=state.role==='manager',isDirector=state.role==='director',isWarehouse=state.role==='warehouse';let actions='';if(isWarehouse||isDirector){actions+=button('＋ Добавить комментарий','add-comment','small-button primary-soft')}
 if(isManager||isDirector){actions+=button('Отметить просмотренным','mark-seen','small-button');if(o.status==='Под вопросом'||o.status==='Собран'||o.status==='На согласовании')actions+=button('На согласовании','set-approval','small-button');if(o.status==='На согласовании'||o.status==='Под вопросом'||o.status==='Собран')actions+=button('Одобрить к отгрузке','approve-order','small-button good');if(o.status!=='Отменён')actions+=button('Отменить заказ','cancel-order','small-button danger')}
 if(isDirector)actions+=button('Удалить карточку','delete-order','small-button danger');let entries=(o.entries||[]).map(e=>`<article class="timeline-item"><div class="timeline-top"><span><b>${esc(e.author)}</b> · ${fmtDateTime(e.createdAt)}</span><span style="display:flex;align-items:center;gap:7px"><span class="timeline-type">${esc(({defect:'ДЕФЕКТ',question:'ВОПРОС',decision:'РЕШЕНИЕ',comment:'КОММЕНТАРИЙ',viewed:'ПРОСМОТРЕНО',system:'СИСТЕМА'})[e.kind]||'ЗАПИСЬ')}</span>${isDirector?`<button class="row-menu" title="Удалить запись (директор)" data-action="delete-entry:${e.id}">×</button>`:''}</span></div>${e.article?`<div class="timeline-article">Артикул: ${esc(e.article)}</div>`:''}<div class="timeline-text">${esc(e.text)}</div>${e.photos?.length?`<div class="photo-grid">${e.photos.map(p=>`<img src="${p}" alt="Фото к записи" data-photo="${p}">`).join('')}</div>`:''}${e.kind==='defect'&&isManager?`<div class="decision-row"><span>Решение по дефекту: <b>${esc(e.decision||'ожидает ответа')}</b>${e.decisionText?`<br>${esc(e.decisionText)}`:''}</span><span class="decision-actions">${button('Подтвердить','defect-confirm:'+e.id,'small-button good')}${button('Отменить','defect-cancel:'+e.id,'small-button danger')}</span></div>`:''}${e.kind==='defect'&&e.decision&&!isManager?`<div class="decision-row"><span>Решение менеджера: <b>${esc(e.decision)}</b>${e.decisionText?`<br>${esc(e.decisionText)}`:''}</span></div>`:''}</article>`).join('');const reviewed=(o.entries||[]).some(e=>e.kind==='viewed');let badge=reviewed?'<span class="status-pill status-neutral">Просмотрен менеджером</span>':'';showModal(`Заказ № ${o.number}`,`<div class="order-detail-head"><div><div class="detail-number">${esc(o.client)}</div><div class="detail-client">Заказ № ${esc(o.number)}</div><div class="detail-meta">Создан ${fmtDateTime(o.createdAt)} · ${esc(o.author||'Кладовщик')}</div></div><div>${statusPill(o.status)}<div style="margin-top:6px">${badge}</div></div></div><div class="detail-actions">${actions}</div><div class="detail-section-title">История · ${entriesCount(o)} ${plural(entriesCount(o),'запись','записи','записей')}</div><div class="timeline">${entries||'<div class="danger-note">Записей пока нет. Добавьте комментарий или описание дефекта.</div>'}</div>`,[button('Закрыть','close')],'КАРТОЧКА ЗАКАЗА')}
function addComment(){const o=state.orders.find(x=>x.id===selectedId);showModal('Добавить запись',`<form id="entryForm"><div class="field"><label for="entryKind">Тип записи</label><select id="entryKind"><option value="comment">Комментарий / вопрос</option><option value="defect">Дефект детали</option></select></div><div class="field" id="articleField" hidden><label for="article">Артикул детали *</label><input id="article" placeholder="Артикул"></div><div class="field"><label for="entryText">Комментарий *</label><textarea id="entryText" required placeholder="Опишите вопрос или дефект"></textarea></div><div class="field"><label for="entryPhotos">Фото (можно выбрать несколько)</label><div class="upload-box">Прикрепите фотографии к записи<input id="entryPhotos" type="file" accept="image/*" multiple></div><span class="field-hint">Фото автоматически сжимаются перед сохранением в общую историю.</span></div></form>`,[button('Назад','back-detail'),button('Сохранить запись','save-entry','primary-button')],'КОММЕНТАРИЙ ИЛИ ДЕФЕКТ');$('entryKind').addEventListener('change',e=>{$('articleField').hidden=e.target.value!=='defect'})}
function saveOrder(){const n=$('orderNumber').value.trim(),client=$('clientName').value.trim();if(!n||!client){toast('Укажите номер заказа и имя клиента.');return}if(state.orders.some(o=>o.number.toLowerCase()===n.toLowerCase())){toast('Карточка с таким номером уже есть.');return}const status=$('startStatus').value,comment=$('initialComment').value.trim();const o={id:crypto.randomUUID(),number:n,client,status,createdAt:isoNow(),author:profileName||roles[state.role],createdBy:signedInUser.uid,entries:[]};if(comment)o.entries.push({id:crypto.randomUUID(),kind:'comment',text:comment,author:profileName||roles[state.role],createdAt:isoNow(),photos:[]});state.orders.unshift(o);save();closeModal();render();toast('Карточка заказа создана.');notify(`Создан заказ № ${n}`,o.id)}
async function readPhotos(files){if(files.length>5)throw new Error('К одной записи можно прикрепить не более пяти фото.');const out=[];let total=0;for(const file of [...files]){if(!file.type.startsWith('image/'))throw new Error('Можно прикреплять только изображения.');const image=await new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Не удалось открыть фото'))};img.src=url});const scale=Math.min(1,1600/Math.max(image.width,image.height)),canvas=document.createElement('canvas');canvas.width=Math.round(image.width*scale);canvas.height=Math.round(image.height*scale);canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);let data=canvas.toDataURL('image/jpeg',.78);while(data.length>280000)data=canvas.toDataURL('image/jpeg',.58);total+=data.length;if(data.length>280000||total>620000)throw new Error('Фото слишком большие вместе. Прикрепите меньше снимков или уменьшите их размер.');out.push(data)}return out}
async function saveEntry(){const kind=$('entryKind').value,text=$('entryText').value.trim(),article=$('article')?.value.trim()||'';if(!text){toast('Добавьте комментарий.');return}if(kind==='defect'&&!article){toast('Для дефекта укажите артикул детали.');return}try{const photos=await readPhotos($('entryPhotos').files);const o=state.orders.find(x=>x.id===selectedId);o.entries.push({id:crypto.randomUUID(),kind,article:kind==='defect'?article:'',text,author:roles[state.role],createdAt:isoNow(),photos});if(kind==='defect')o.status='Под вопросом';save();closeModal();render();toast('Запись добавлена в историю заказа.');notify(`${kind==='defect'?'Дефект':'Комментарий'} к заказу № ${o.number}`,o.id);openOrder(o.id)}catch(e){toast(e.message)}}
function setStatus(status,text,kind='system'){const o=state.orders.find(x=>x.id===selectedId);if(!o)return;o.status=status;o.entries.push({id:crypto.randomUUID(),kind,text,author:roles[state.role],createdAt:isoNow(),photos:[]});save();render();toast(`Статус: ${status}`);notify(`Заказ № ${o.number}: ${status}`,o.id);openOrder(o.id)}
function cancelOrder(){const o=state.orders.find(x=>x.id===selectedId);showModal('Отменить заказ',`<p style="font-size:12px;color:#697382;margin:0 0 14px">Укажите причину отмены заказа № ${esc(o.number)}. Причина сохранится в истории.</p><div class="field"><label for="cancelReason">Причина отмены *</label><textarea id="cancelReason" required placeholder="Почему заказ отменён?"></textarea></div>`,[button('Назад','back-detail'),button('Отменить заказ','confirm-cancel','small-button danger')],'РЕШЕНИЕ МЕНЕДЖЕРА')}
function approveOrder(){showModal('Одобрить на отгрузку',`<p style="font-size:12px;color:#697382;margin:0 0 12px">Заказ № ${esc(state.orders.find(x=>x.id===selectedId)?.number||'')} будет отмечен как одобренный к отгрузке клиенту.</p><div class="field"><label for="approvalComment">Комментарий менеджера (необязательно)</label><textarea id="approvalComment" placeholder="Добавьте пояснение для кладовщика"></textarea></div>`,[button('Назад','back-detail'),button('Одобрить','confirm-approve','small-button good')],'РЕШЕНИЕ МЕНЕДЖЕРА')}
function confirmApprove(){const note=$('approvalComment').value.trim()||'Согласовано к отгрузке клиенту.';setStatus('Одобрен на отгрузку клиенту',note,'decision')}
function confirmCancel(){const reason=$('cancelReason').value.trim();if(!reason){toast('Напишите причину отмены.');return}setStatus('Отменён',reason,'decision')}
function markViewed(){const o=state.orders.find(x=>x.id===selectedId);if(o.entries.some(e=>e.kind==='viewed'&&e.authorId===signedInUser.uid)){toast('Вы уже отмечали этот заказ просмотренным.');return}o.entries.push({id:crypto.randomUUID(),kind:'viewed',text:'Менеджер отметил, что увидел собранный заказ.',author:roles[state.role],createdAt:isoNow(),photos:[]});save();render();notify(`Менеджер просмотрел заказ № ${o.number}`,o.id);openOrder(o.id)}
function decideDefect(entryId,decision){const o=state.orders.find(x=>x.id===selectedId),e=o.entries.find(x=>x.id===entryId);if(decision==='Отменён'){showModal('Отменить заказ',`<p style="font-size:12px;color:#697382;margin:0 0 12px">Напишите причину отмены заказа № ${esc(o.number)} по дефекту артикула ${esc(e.article)}.</p><div class="field"><label for="defectReason">Причина отмены *</label><textarea id="defectReason" required placeholder="Почему заказ отменён?"></textarea></div>`,[button('Назад','back-detail'),button('Отменить заказ','confirm-defect-cancel','small-button danger')],'ОТМЕНА ЗАКАЗА');return}e.decision='Подтверждён';e.decisionText='Дефект согласован менеджером.';e.decidedBy=roles[state.role];e.decidedAt=isoNow();const defects=o.entries.filter(x=>x.kind==='defect');if(defects.every(x=>x.decision==='Подтверждён'))o.status='Одобрен на отгрузку клиенту';save();render();notify(`Дефект артикула ${e.article} по заказу № ${o.number} подтверждён${o.status==='Одобрен на отгрузку клиенту'?' — заказ одобрен к отгрузке':''}`,o.id);openOrder(o.id)}
function confirmDefectCancel(){const reason=$('defectReason').value.trim();if(!reason){toast('Укажите причину решения.');return}const o=state.orders.find(x=>x.id===selectedId),e=o.entries.find(x=>x.id===pendingDefectId);if(!e)return;e.decision='Отменён';e.decisionText=reason;e.decidedBy=roles[state.role];e.decidedAt=isoNow();o.status='Отменён';pendingDefectId=null;save();render();notify(`Заказ № ${o.number} отменён по дефекту артикула ${e.article}: ${reason}`,o.id);toast('Кладовщик получит уведомление об отмене заказа.');openOrder(o.id)}
function deleteOrder(){const o=state.orders.find(x=>x.id===selectedId);showModal('Удалить карточку?',`<div class="danger-note">Будет зафиксировано, что директор ${esc(roles[state.role])} удалил заказ № ${esc(o.number)}. Удалённая карточка исчезнет из обычного списка.</div>`,[button('Назад','back-detail'),button('Удалить карточку','confirm-delete','small-button danger')],'ДЕЙСТВИЕ ДИРЕКТОРА')}
function deleteEntry(entryId){const o=state.orders.find(x=>x.id===selectedId),entry=o.entries.find(x=>x.id===entryId);if(!entry||state.role!=='director')return;showModal('Удалить запись?',`<div class="danger-note">Комментарий и прикреплённые к нему фото будут удалены. Действие попадёт в журнал директора.</div>`,[button('Назад','back-detail'),button('Удалить запись','confirm-delete-entry:'+entryId,'small-button danger')],'ДЕЙСТВИЕ ДИРЕКТОРА')}
function confirmDeleteEntry(entryId){const o=state.orders.find(x=>x.id===selectedId),entry=o.entries.find(x=>x.id===entryId);if(!entry)return;const label=entry.article?`дефект артикула ${entry.article}`:({comment:'комментарий',question:'вопрос',decision:'решение',viewed:'отметку о просмотре'})[entry.kind]||'запись';o.entries=o.entries.filter(x=>x.id!==entryId);state.notices.unshift({id:crypto.randomUUID(),message:`Директор удалил ${label} из заказа № ${o.number}`,orderId:null,at:isoNow(),read:false,kind:'audit'});save();render();toast('Удаление внесено в журнал действий.');openOrder(o.id)}
function confirmDelete(){const o=state.orders.find(x=>x.id===selectedId);state.orders=state.orders.filter(x=>x.id!==selectedId);state.notices.unshift({id:crypto.randomUUID(),message:`Директор удалил заказ № ${o.number}`,orderId:null,at:isoNow(),read:false,kind:'audit'});save();closeModal();render();toast('Удаление внесено в журнал действий.')}
function paintNotices(){const unread=state.notices.some(n=>!n.read);$('notificationButton').classList.toggle('has-notice',unread)}
function showNotifications(){state.notices.forEach(n=>n.read=true);paintNotices();showModal('Уведомления',state.notices.length?`<div class="notice-list">${state.notices.map(n=>`<div class="notice-item">${esc(n.message)}<small>${fmtDateTime(n.at)}</small></div>`).join('')}</div>`:'<div class="danger-note">Новых уведомлений пока нет.</div>',[button('Разрешить на этом устройстве','enable-notifications','small-button'),button('Готово','close')],'ЦЕНТР УВЕДОМЛЕНИЙ')}
function profileMenu(){const adminAction=canManageUsers?button('Учётные записи сотрудников','open-staff','small-button primary-soft'):'';showModal('Учётная запись',`<p style="font-size:13px;color:#52635a;margin:0 0 6px"><b>${esc(profileName)}</b><br>${esc(signedInUser?.email||'')} · ${esc(roles[state.role])}${canManageUsers?' · администратор':''}</p>`,[adminAction,button('Выйти','sign-out','small-button danger'),button('Закрыть','close')],'ПРОФИЛЬ СОТРУДНИКА')}
async function showStaff(){if(!canManageUsers)return;try{const snap=await getDocs(collection(db,'users'));const people=snap.docs.map(d=>({uid:d.id,...d.data()})).sort((a,b)=>String(a.displayName||'').localeCompare(String(b.displayName||''),'ru'));const rows=people.map(p=>`<div class="notice-item"><b>${esc(p.displayName||'Без имени')}</b><small>${esc(p.email||'')} · ${esc(p.role||'роль не задана')} · ${p.active?'Активен':'Отключён'}${p.admin?' · Администратор':''}</small>${p.uid!==signedInUser.uid?`<button class="small-button ${p.active?'danger':'good'}" data-action="toggle-user:${esc(p.uid)}:${p.active?'off':'on'}">${p.active?'Отключить':'Включить'}</button>`:''}</div>`).join('');showModal('Учётные записи сотрудников',`<div class="notice-list">${rows||'<div class="danger-note">Пока нет сотрудников.</div>'}</div>`,[button('Назад','back-profile'),button('＋ Добавить сотрудника','new-staff','primary-button')],'АДМИНИСТРИРОВАНИЕ') }catch(err){console.error(err);toast('Не удалось загрузить список сотрудников.')}}
function newStaff(){if(!canManageUsers)return;const rolesOptions=`<option value="warehouse">Кладовщик</option><option value="manager">Менеджер</option>${canManageUsers?'<option value="director">Директор</option>':''}`;showModal('Добавить сотрудника',`<form id="staffForm"><div class="field"><label for="staffName">Имя сотрудника *</label><input id="staffName" required autocomplete="off"></div><div class="field"><label for="staffEmail">Рабочая почта *</label><input id="staffEmail" type="email" required autocomplete="off"></div><p class="field-hint">Сотруднику на эту почту будет отправлена ссылка для установки пароля.</p><div class="field"><label for="staffRole">Роль</label><select id="staffRole">${rolesOptions}</select></div></form>`,[button('Назад','open-staff'),button('Создать учётную запись','create-staff','primary-button')],'НОВЫЙ СОТРУДНИК')}
async function createStaff(){const displayName=$('staffName').value.trim(),email=$('staffEmail').value.trim(),role=$('staffRole').value;if(!displayName||!email){toast('Заполните имя и рабочую почту.');return}if(!canManageUsers){toast('У вас нет прав назначить эту роль.');return}let stage='создание аккаунта';try{const temporaryPassword=crypto.randomUUID()+'aA1!';const created=await createUserWithEmailAndPassword(staffAuth,email,temporaryPassword);stage='сохранение профиля';await setDoc(doc(db,'users',created.user.uid),{displayName,email,role,active:true,admin:false});if(staffAuth.currentUser)await signOut(staffAuth);stage='отправка письма';await sendPasswordResetEmail(auth,email);toast('Сотрудник добавлен; ссылка для установки пароля отправлена ему на почту. Проверьте папку «Спам», если письма нет.');showStaff()}catch(err){console.error('Не удалось завершить создание сотрудника',stage,err);const reasons={'auth/email-already-in-use':'Такая почта уже зарегистрирована.','auth/invalid-email':'Проверьте адрес почты.','auth/weak-password':'Не удалось создать надёжный пароль.','auth/operation-not-allowed':'В Firebase не включён вход по почте и паролю.','auth/unauthorized-continue-uri':'В Firebase не разрешён адрес возврата для письма.','auth/invalid-continue-uri':'Неверный адрес возврата для письма.','auth/too-many-requests':'Firebase временно ограничил отправку. Попробуйте позже.','auth/network-request-failed':'Не удалось связаться с Firebase. Проверьте подключение.'};const detail=reasons[err.code]||`${err.code||'ошибка Firebase'}${err.message?`: ${err.message}`:''}`;toast(`Не удалось завершить ${stage}: ${detail}`);if(stage==='отправка письма')toast('Аккаунт и профиль созданы. Повторите «Забыли пароль?» на экране входа или проверьте шаблон писем Firebase.')}finally{if(staffAuth.currentUser)await signOut(staffAuth)}}
function backProfile(){closeModal();profileMenu()}
async function toggleStaff(uid,active){if(!canManageUsers||uid===signedInUser.uid)return;try{await updateDoc(doc(db,'users',uid),{active});toast(active?'Доступ сотрудника включён.':'Доступ сотрудника отключён.');showStaff()}catch(err){console.error(err);toast('Не удалось изменить доступ сотрудника.')}}
function backDetail(){closeModal();openOrder(selectedId)}
document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open){e.preventDefault();openOrder(open.dataset.open);return}const nav=e.target.closest('.nav-item');if(nav){activeFilter=nav.dataset.filter;render();closeSidebar();return}if(e.target===$('sidebarBackdrop')){closeSidebar();return}const act=e.target.closest('[data-action]')?.dataset.action;if(act){if(act==='close')closeModal();else if(act==='create-order')saveOrder();else if(act==='add-comment')addComment();else if(act==='back-detail')backDetail();else if(act==='save-entry')saveEntry();else if(act==='set-approval')setStatus('На согласовании','Начал согласование заказа с клиентом.');else if(act==='approve-order')approveOrder();else if(act==='confirm-approve')confirmApprove();else if(act==='cancel-order')cancelOrder();else if(act==='confirm-cancel')confirmCancel();else if(act==='mark-seen')markViewed();else if(act==='delete-order')deleteOrder();else if(act==='confirm-delete')confirmDelete();else if(act.startsWith('delete-entry:'))deleteEntry(act.split(':')[1]);else if(act.startsWith('confirm-delete-entry:'))confirmDeleteEntry(act.split(':')[1]);else if(act==='confirm-defect-cancel')confirmDefectCancel();else if(act==='sign-out'){closeModal();signOut(auth)}else if(act==='open-staff')showStaff();else if(act==='new-staff')newStaff();else if(act==='create-staff')createStaff();else if(act==='back-profile')backProfile();else if(act.startsWith('toggle-user:')){const[,uid,mode]=act.split(':');toggleStaff(uid,mode==='on')}else if(act==='enable-notifications'){if(!('Notification'in window))toast('Браузер не поддерживает уведомления.');else Notification.requestPermission().then(p=>toast(p==='granted'?'Уведомления разрешены на этом устройстве.':'Разрешение не предоставлено.'))}else if(act.startsWith('defect-confirm:'))decideDefect(act.split(':')[1],'Подтверждён');else if(act.startsWith('defect-cancel:')){pendingDefectId=act.split(':')[1];decideDefect(pendingDefectId,'Отменён')}return}if(e.target===modal)closeModal();const photo=e.target.closest('[data-photo]');if(photo)window.open(photo.dataset.photo,'_blank','noopener')});
let sidebarHistoryEntry=false,handlingSidebarPop=false;function closeSidebar(fromPop=false){$('sidebar').classList.remove('open');$('sidebarBackdrop').hidden=true;if(sidebarHistoryEntry&&!fromPop){handlingSidebarPop=true;history.back()}sidebarHistoryEntry=false}
function openSidebar(){if($('sidebar').classList.contains('open')){closeSidebar();return}$('sidebar').classList.add('open');$('sidebarBackdrop').hidden=false;history.pushState({mobileSidebar:true},'','#menu');sidebarHistoryEntry=true}
window.addEventListener('popstate',()=>{if($('sidebar').classList.contains('open'))closeSidebar(true);else if(handlingSidebarPop)handlingSidebarPop=false});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeSidebar()});
$('newOrderButton').addEventListener('click',openNewOrder);$('emptyAddButton').addEventListener('click',openNewOrder);$('closeModal').addEventListener('click',closeModal);$('searchInput').addEventListener('input',render);$('notificationButton').addEventListener('click',showNotifications);$('profileButton').addEventListener('click',profileMenu);$('mobileMenu').addEventListener('click',openSidebar);$('filterButton').addEventListener('click',()=>{const filters=['all','Под вопросом','На согласовании','Одобрен на отгрузку клиенту','Отменён'];const idx=filters.indexOf(activeFilter);activeFilter=filters[(idx+1)%filters.length];render();toast(activeFilter==='all'?'Показаны все заказы':`Фильтр: ${activeFilter}`)});document.addEventListener('submit',e=>e.preventDefault());
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
showAuth();
