const STORE_KEY='order-desk-demo-v1';
const roles={warehouse:'Кладовщик',manager:'Менеджер',director:'Директор'};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isoNow=()=>new Date().toISOString();
const fmtDate=d=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d));
const fmtDateTime=d=>new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(d));
const demoSeed=[
 {id:'demo-1',number:'ЗК-18472',client:'ТОВ «Альфа Трейд»',status:'Под вопросом',createdAt:'2026-09-29T08:42:00.000Z',author:'Кладовщик',entries:[{id:'e1',kind:'defect',article:'BR-2048',text:'На корпусе трещина рядом с креплением. Нужна проверка перед отгрузкой.',author:'Кладовщик',createdAt:'2026-09-29T08:45:00.000Z',photos:[]}]},
 {id:'demo-2',number:'ЗК-18469',client:'Магазин «Вектор»',status:'На согласовании',createdAt:'2026-09-29T07:30:00.000Z',author:'Кладовщик',entries:[{id:'e2',kind:'comment',text:'Подскажите, можно ли заменить позицию на аналог?',author:'Кладовщик',createdAt:'2026-09-29T07:34:00.000Z',photos:[]}]},
 {id:'demo-3',number:'ЗК-18463',client:'ФОП Коваленко',status:'Одобрен на отгрузку клиенту',createdAt:'2026-09-28T14:18:00.000Z',author:'Кладовщик',entries:[{id:'e3',kind:'comment',text:'Собран, проверен, готов к отгрузке.',author:'Кладовщик',createdAt:'2026-09-28T14:20:00.000Z',photos:[]},{id:'e4',kind:'decision',text:'Отгрузку согласовал. Клиент ожидает доставку завтра.',author:'Менеджер',createdAt:'2026-09-28T15:05:00.000Z',photos:[]}]}
];
function loadState(){try{const s=JSON.parse(localStorage.getItem(STORE_KEY));if(s&&Array.isArray(s.orders))return s}catch{}return{orders:demoSeed,notices:[],role:'warehouse',seen:{}}}
let state=loadState(), activeFilter='all', selectedId=null, pendingDefectId=null;
const $=id=>document.getElementById(id), modal=$('modalBackdrop');
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state))}
function initials(name){return String(name).split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase()}
function notify(message,orderId){state.notices.unshift({id:crypto.randomUUID(),message,orderId,at:isoNow(),read:false});state.notices=state.notices.slice(0,50);save();paintNotices()}
function statusClass(s){return({'Собран':'status-assembled','Под вопросом':'status-question','На согласовании':'status-approval','Одобрен на отгрузку клиенту':'status-ready','Отменён':'status-cancel'})[s]||'status-neutral'}
function statusPill(s){return `<span class="status-pill ${statusClass(s)}">${esc(s)}</span>`}
function entriesCount(o){return(o.entries||[]).length}
function render(){const search=$('searchInput').value.toLocaleLowerCase('ru');let orders=[...state.orders].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));if(activeFilter!=='all')orders=orders.filter(o=>o.status===activeFilter);if(search)orders=orders.filter(o=>(o.number+' '+o.client).toLocaleLowerCase('ru').includes(search));$('ordersBody').innerHTML=orders.map(o=>`<tr data-order="${esc(o.id)}"><td><a class="order-number" href="#" data-open="${esc(o.id)}">№ ${esc(o.number)}</a><span class="client-sub">создал ${esc(o.author||'Кладовщик')}</span></td><td><span class="client-name">${esc(o.client)}</span><span class="client-sub">${fmtDateTime(o.createdAt)}</span></td><td>${statusPill(o.status)}</td><td><span class="entry-count">${entriesCount(o)}</span></td><td class="time-cell">${fmtDate(o.createdAt)}</td><td><button class="row-menu" title="Открыть карточку" data-open="${esc(o.id)}">···</button></td></tr>`).join('');const empty=orders.length===0;$('emptyState').classList.toggle('visible',empty);$('ordersBody').style.display=empty?'none':'';$('statTotal').textContent=state.orders.length;$('statQuestions').textContent=state.orders.filter(o=>o.status==='Под вопросом').length;$('statApproval').textContent=state.orders.filter(o=>o.status==='На согласовании').length;$('statReady').textContent=state.orders.filter(o=>o.status==='Одобрен на отгрузку клиенту').length;$('allCount').textContent=state.orders.length;$('questionCount').textContent=state.orders.filter(o=>o.status==='Под вопросом').length;$('listSummary').textContent=`${orders.length} ${plural(orders.length,'заказ','заказа','заказов')}`;$('userName').textContent=roles[state.role];$('userRole').textContent=state.role==='warehouse'?'Администратор':state.role==='director'?'Полный доступ':'Согласование';$('modeLabel').textContent='Демо-режим';$('modeSub').textContent='Данные только на этом устройстве';$('today').textContent=new Intl.DateTimeFormat('ru-RU',{weekday:'short',day:'numeric',month:'long'}).format(new Date());document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.filter===activeFilter));paintNotices()}
function plural(n,a,b,c){n=Math.abs(n)%100;const d=n%10;return n>10&&n<20?c:d>1&&d<5?b:d===1?a:c}
function toast(msg){const t=document.createElement('div');t.className='toast';t.textContent=msg;$('toastStack').append(t);setTimeout(()=>t.remove(),3500)}
function showModal(title,body,buttons=[],eyebrow='КАРТОЧКА ЗАКАЗА'){ $('modalTitle').textContent=title;$('modalEyebrow').textContent=eyebrow;$('modalBody').innerHTML=body;$('modalFoot').innerHTML=buttons.join('');modal.hidden=false;document.body.style.overflow='hidden'}
function closeModal(){modal.hidden=true;document.body.style.overflow=''}
function button(label,action,cls='small-button'){return `<button class="${cls}" data-action="${action}">${label}</button>`}
function openNewOrder(){if(state.role==='manager'){toast('Создавать карточки в этой версии может кладовщик.');return}showModal('Добавить заказ',`<form id="newOrderForm"><div class="form-grid"><div class="field"><label for="orderNumber">Номер заказа *</label><input id="orderNumber" required placeholder="Например, ЗК-18472" autocomplete="off"></div><div class="field"><label for="clientName">Имя клиента *</label><input id="clientName" required placeholder="Имя или название компании"></div></div><div class="field"><label for="startStatus">Начальный статус</label><select id="startStatus"><option>Собран</option><option>Под вопросом</option></select><span class="field-hint">Выберите «Под вопросом», если добавите дефект или вопрос менеджеру.</span></div><div class="field"><label for="initialComment">Комментарий (необязательно)</label><textarea id="initialComment" placeholder="Короткая заметка по заказу"></textarea></div></form>`,[button('Отмена','close'),button('Создать карточку','create-order','primary-button')],'НОВЫЙ ЗАКАЗ')}
function openOrder(id){const o=state.orders.find(x=>x.id===id);if(!o)return;selectedId=id;const isManager=state.role==='manager',isDirector=state.role==='director',isWarehouse=state.role==='warehouse';let actions='';if(isWarehouse||isDirector){actions+=button('＋ Добавить комментарий','add-comment','small-button primary-soft')}
 if(isManager||isDirector){actions+=button('Отметить просмотренным','mark-seen','small-button');if(o.status==='Под вопросом'||o.status==='Собран'||o.status==='На согласовании')actions+=button('На согласовании','set-approval','small-button');if(o.status==='На согласовании'||o.status==='Под вопросом'||o.status==='Собран')actions+=button('Одобрить к отгрузке','set-ready','small-button good');if(o.status!=='Отменён')actions+=button('Отменить заказ','cancel-order','small-button danger')}
 if(isDirector)actions+=button('Удалить карточку','delete-order','small-button danger');let entries=(o.entries||[]).map(e=>`<article class="timeline-item"><div class="timeline-top"><span><b>${esc(e.author)}</b> · ${fmtDateTime(e.createdAt)}</span><span style="display:flex;align-items:center;gap:7px"><span class="timeline-type">${esc(({defect:'ДЕФЕКТ',question:'ВОПРОС',decision:'РЕШЕНИЕ',comment:'КОММЕНТАРИЙ',viewed:'ПРОСМОТРЕНО',system:'СИСТЕМА'})[e.kind]||'ЗАПИСЬ')}</span>${isDirector?`<button class="row-menu" title="Удалить запись (директор)" data-action="delete-entry:${e.id}">×</button>`:''}</span></div>${e.article?`<div class="timeline-article">Артикул: ${esc(e.article)}</div>`:''}<div class="timeline-text">${esc(e.text)}</div>${e.photos?.length?`<div class="photo-grid">${e.photos.map(p=>`<img src="${p}" alt="Фото к записи" data-photo="${p}">`).join('')}</div>`:''}${e.kind==='defect'&&isManager?`<div class="decision-row"><span>Решение по дефекту: <b>${esc(e.decision||'ожидает ответа')}</b>${e.decisionText?`<br>${esc(e.decisionText)}`:''}</span><span class="decision-actions">${button('Подтвердить','defect-confirm:'+e.id,'small-button good')}${button('Отменить','defect-cancel:'+e.id,'small-button danger')}</span></div>`:''}${e.kind==='defect'&&e.decision&&!isManager?`<div class="decision-row"><span>Решение менеджера: <b>${esc(e.decision)}</b>${e.decisionText?`<br>${esc(e.decisionText)}`:''}</span></div>`:''}</article>`).join('');const reviewed=(o.entries||[]).some(e=>e.kind==='viewed');let badge=reviewed?'<span class="status-pill status-neutral">Просмотрен менеджером</span>':'';showModal(`Заказ № ${o.number}`,`<div class="order-detail-head"><div><div class="detail-number">${esc(o.client)}</div><div class="detail-client">Заказ № ${esc(o.number)}</div><div class="detail-meta">Создан ${fmtDateTime(o.createdAt)} · ${esc(o.author||'Кладовщик')}</div></div><div>${statusPill(o.status)}<div style="margin-top:6px">${badge}</div></div></div><div class="detail-actions">${actions}</div><div class="detail-section-title">История · ${entriesCount(o)} ${plural(entriesCount(o),'запись','записи','записей')}</div><div class="timeline">${entries||'<div class="danger-note">Записей пока нет. Добавьте комментарий или описание дефекта.</div>'}</div>`,[button('Закрыть','close')],'КАРТОЧКА ЗАКАЗА')}
function addComment(){const o=state.orders.find(x=>x.id===selectedId);showModal('Добавить запись',`<form id="entryForm"><div class="field"><label for="entryKind">Тип записи</label><select id="entryKind"><option value="comment">Комментарий / вопрос</option><option value="defect">Дефект детали</option></select></div><div class="field" id="articleField" hidden><label for="article">Артикул детали *</label><input id="article" placeholder="Артикул"></div><div class="field"><label for="entryText">Комментарий *</label><textarea id="entryText" required placeholder="Опишите вопрос или дефект"></textarea></div><div class="field"><label for="entryPhotos">Фото (можно выбрать несколько)</label><div class="upload-box">Прикрепите фотографии к записи<input id="entryPhotos" type="file" accept="image/*" multiple></div><span class="field-hint">Для демо-предпросмотра — до 1,5 МБ на каждое фото.</span></div></form>`,[button('Назад','back-detail'),button('Сохранить запись','save-entry','primary-button')],'КОММЕНТАРИЙ ИЛИ ДЕФЕКТ');$('entryKind').addEventListener('change',e=>{$('articleField').hidden=e.target.value!=='defect'})}
function saveOrder(){const n=$('orderNumber').value.trim(),client=$('clientName').value.trim();if(!n||!client){toast('Укажите номер заказа и имя клиента.');return}if(state.orders.some(o=>o.number.toLowerCase()===n.toLowerCase())){toast('Карточка с таким номером уже есть.');return}const status=$('startStatus').value,comment=$('initialComment').value.trim();const o={id:crypto.randomUUID(),number:n,client,status,createdAt:isoNow(),author:roles[state.role],entries:[]};if(comment)o.entries.push({id:crypto.randomUUID(),kind:'comment',text:comment,author:roles[state.role],createdAt:isoNow(),photos:[]});state.orders.unshift(o);save();closeModal();render();toast('Карточка заказа создана.');notify(`Создан заказ № ${n}`,o.id)}
function readPhotos(files){return Promise.all([...files].map(file=>new Promise((resolve,reject)=>{if(file.size>1.5*1024*1024){reject(new Error(`Фото «${file.name}» больше 1,5 МБ`));return}const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Не удалось прочитать фото'));r.readAsDataURL(file)})))}
async function saveEntry(){const kind=$('entryKind').value,text=$('entryText').value.trim(),article=$('article')?.value.trim()||'';if(!text){toast('Добавьте комментарий.');return}if(kind==='defect'&&!article){toast('Для дефекта укажите артикул детали.');return}try{const photos=await readPhotos($('entryPhotos').files);const o=state.orders.find(x=>x.id===selectedId);o.entries.push({id:crypto.randomUUID(),kind,article:kind==='defect'?article:'',text,author:roles[state.role],createdAt:isoNow(),photos});if(kind==='defect')o.status='Под вопросом';save();closeModal();render();toast('Запись добавлена в историю заказа.');notify(`${kind==='defect'?'Дефект':'Комментарий'} к заказу № ${o.number}`,o.id);openOrder(o.id)}catch(e){toast(e.message)}}
function setStatus(status,text,kind='system'){const o=state.orders.find(x=>x.id===selectedId);if(!o)return;o.status=status;o.entries.push({id:crypto.randomUUID(),kind,text,author:roles[state.role],createdAt:isoNow(),photos:[]});save();render();toast(`Статус: ${status}`);notify(`Заказ № ${o.number}: ${status}`,o.id);openOrder(o.id)}
function cancelOrder(){const o=state.orders.find(x=>x.id===selectedId);showModal('Отменить заказ',`<p style="font-size:12px;color:#697382;margin:0 0 14px">Укажите причину отмены заказа № ${esc(o.number)}. Причина сохранится в истории.</p><div class="field"><label for="cancelReason">Причина отмены *</label><textarea id="cancelReason" required placeholder="Почему заказ отменён?"></textarea></div>`,[button('Назад','back-detail'),button('Отменить заказ','confirm-cancel','small-button danger')],'РЕШЕНИЕ МЕНЕДЖЕРА')}
function confirmCancel(){const reason=$('cancelReason').value.trim();if(!reason){toast('Напишите причину отмены.');return}setStatus('Отменён',reason,'decision')}
function markViewed(){const o=state.orders.find(x=>x.id===selectedId);if(o.entries.some(e=>e.kind==='viewed'&&e.author===roles[state.role])){toast('Вы уже отмечали этот заказ просмотренным.');return}o.entries.push({id:crypto.randomUUID(),kind:'viewed',text:'Менеджер отметил, что увидел собранный заказ.',author:roles[state.role],createdAt:isoNow(),photos:[]});save();render();notify(`Менеджер просмотрел заказ № ${o.number}`,o.id);openOrder(o.id)}
function decideDefect(entryId,decision){const o=state.orders.find(x=>x.id===selectedId),e=o.entries.find(x=>x.id===entryId);if(decision==='Отменён'){showModal('Отменить заказ',`<p style="font-size:12px;color:#697382;margin:0 0 12px">Напишите причину отмены заказа № ${esc(o.number)} по дефекту артикула ${esc(e.article)}.</p><div class="field"><label for="defectReason">Причина отмены *</label><textarea id="defectReason" required placeholder="Почему заказ отменён?"></textarea></div>`,[button('Назад','back-detail'),button('Отменить заказ','confirm-defect-cancel','small-button danger')],'ОТМЕНА ЗАКАЗА');return}e.decision='Подтверждён';e.decisionText='Дефект согласован менеджером.';e.decidedBy=roles[state.role];e.decidedAt=isoNow();const defects=o.entries.filter(x=>x.kind==='defect');if(defects.every(x=>x.decision==='Подтверждён'))o.status='Одобрен на отгрузку клиенту';save();render();notify(`Дефект артикула ${e.article} по заказу № ${o.number} подтверждён${o.status==='Одобрен на отгрузку клиенту'?' — заказ одобрен к отгрузке':''}`,o.id);openOrder(o.id)}
function confirmDefectCancel(){const reason=$('defectReason').value.trim();if(!reason){toast('Укажите причину решения.');return}const o=state.orders.find(x=>x.id===selectedId),e=o.entries.find(x=>x.id===pendingDefectId);if(!e)return;e.decision='Отменён';e.decisionText=reason;e.decidedBy=roles[state.role];e.decidedAt=isoNow();o.status='Отменён';pendingDefectId=null;save();render();notify(`Заказ № ${o.number} отменён по дефекту артикула ${e.article}: ${reason}`,o.id);toast('Кладовщик получит уведомление об отмене заказа.');openOrder(o.id)}
function deleteOrder(){const o=state.orders.find(x=>x.id===selectedId);showModal('Удалить карточку?',`<div class="danger-note">Будет зафиксировано, что директор ${esc(roles[state.role])} удалил заказ № ${esc(o.number)}. Удалённая карточка исчезнет из обычного списка.</div>`,[button('Назад','back-detail'),button('Удалить карточку','confirm-delete','small-button danger')],'ДЕЙСТВИЕ ДИРЕКТОРА')}
function deleteEntry(entryId){const o=state.orders.find(x=>x.id===selectedId),entry=o.entries.find(x=>x.id===entryId);if(!entry||state.role!=='director')return;showModal('Удалить запись?',`<div class="danger-note">Комментарий и прикреплённые к нему фото будут удалены. Действие попадёт в журнал директора.</div>`,[button('Назад','back-detail'),button('Удалить запись','confirm-delete-entry:'+entryId,'small-button danger')],'ДЕЙСТВИЕ ДИРЕКТОРА')}
function confirmDeleteEntry(entryId){const o=state.orders.find(x=>x.id===selectedId),entry=o.entries.find(x=>x.id===entryId);if(!entry)return;const label=entry.article?`дефект артикула ${entry.article}`:({comment:'комментарий',question:'вопрос',decision:'решение',viewed:'отметку о просмотре'})[entry.kind]||'запись';o.entries=o.entries.filter(x=>x.id!==entryId);state.notices.unshift({id:crypto.randomUUID(),message:`Директор удалил ${label} из заказа № ${o.number}`,orderId:null,at:isoNow(),read:false,kind:'audit'});save();render();toast('Удаление внесено в журнал действий.');openOrder(o.id)}
function confirmDelete(){const o=state.orders.find(x=>x.id===selectedId);state.orders=state.orders.filter(x=>x.id!==selectedId);state.notices.unshift({id:crypto.randomUUID(),message:`Директор удалил заказ № ${o.number}`,orderId:null,at:isoNow(),read:false,kind:'audit'});save();closeModal();render();toast('Удаление внесено в журнал действий.')}
function paintNotices(){const unread=state.notices.some(n=>!n.read);$('notificationButton').classList.toggle('has-notice',unread)}
function showNotifications(){state.notices.forEach(n=>n.read=true);save();showModal('Уведомления',state.notices.length?`<div class="notice-list">${state.notices.map(n=>`<div class="notice-item">${esc(n.message)}<small>${fmtDateTime(n.at)}</small></div>`).join('')}</div>`:'<div class="danger-note">Новых уведомлений пока нет.</div>',[button('Готово','close')],'ЦЕНТР УВЕДОМЛЕНИЙ')}
function profileMenu(){showModal('Предпросмотр ролей',`<p style="font-size:11px;color:#74808e;margin-top:0">В демонстрационном режиме можно переключать роли, чтобы посмотреть доступные действия. В подключённом приложении роли назначает администратор.</p><div class="role-choice">${Object.entries(roles).map(([k,v])=>`<button class="${state.role===k?'selected':''}" data-role="${k}">${v}</button>`).join('')}</div>`,[button('Закрыть','close')],'ДЕМО-ПРОФИЛЬ')}
function backDetail(){closeModal();openOrder(selectedId)}
document.addEventListener('click',e=>{const open=e.target.closest('[data-open]');if(open){e.preventDefault();openOrder(open.dataset.open);return}const nav=e.target.closest('.nav-item');if(nav){activeFilter=nav.dataset.filter;render();return}const act=e.target.closest('[data-action]')?.dataset.action;if(act){if(act==='close')closeModal();else if(act==='create-order')saveOrder();else if(act==='add-comment')addComment();else if(act==='back-detail')backDetail();else if(act==='save-entry')saveEntry();else if(act==='set-approval')setStatus('На согласовании','Начал согласование заказа с клиентом.');else if(act==='set-ready')setStatus('Одобрен на отгрузку клиенту','Согласовано к отгрузке клиенту.','decision');else if(act==='cancel-order')cancelOrder();else if(act==='confirm-cancel')confirmCancel();else if(act==='mark-seen')markViewed();else if(act==='delete-order')deleteOrder();else if(act==='confirm-delete')confirmDelete();else if(act.startsWith('delete-entry:'))deleteEntry(act.split(':')[1]);else if(act.startsWith('confirm-delete-entry:'))confirmDeleteEntry(act.split(':')[1]);else if(act==='confirm-defect-cancel')confirmDefectCancel();else if(act.startsWith('defect-confirm:'))decideDefect(act.split(':')[1],'Подтверждён');else if(act.startsWith('defect-cancel:')){pendingDefectId=act.split(':')[1];decideDefect(pendingDefectId,'Отменён')}return}const role=e.target.closest('[data-role]');if(role){state.role=role.dataset.role;save();closeModal();render();return}if(e.target===modal)closeModal();const photo=e.target.closest('[data-photo]');if(photo)window.open(photo.dataset.photo,'_blank','noopener')});
$('newOrderButton').addEventListener('click',openNewOrder);$('emptyAddButton').addEventListener('click',openNewOrder);$('closeModal').addEventListener('click',closeModal);$('searchInput').addEventListener('input',render);$('notificationButton').addEventListener('click',showNotifications);$('profileButton').addEventListener('click',profileMenu);$('mobileMenu').addEventListener('click',()=>$('sidebar').classList.toggle('open'));$('filterButton').addEventListener('click',()=>{const filters=['all','Под вопросом','На согласовании','Одобрен на отгрузку клиенту','Отменён'];const idx=filters.indexOf(activeFilter);activeFilter=filters[(idx+1)%filters.length];render();toast(activeFilter==='all'?'Показаны все заказы':`Фильтр: ${activeFilter}`)});document.addEventListener('submit',e=>e.preventDefault());
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
render();
